scope: all
title: "Journey away from smartphones"
subtitle: "Regaining focus"
author: Tom Johnson
url_tagline: idratherbewriting.com/smartphones
media: /Users/tomjohnson/projects/idratherbewriting/images/
type: pdf
# if cover is set to true, the title and subtitle aren't used. instead, the cover_image is used instead.
cover_hybrid: true
cover_image: images/journeyawayfromsmartphonestitle.png

sidebar: sidebar_smartphones
baseurl: /Users/tomjohnson/projects/idratherbewriting/_site

language: english
format: print

destination: _site
port: 4000
highlighter: rouge
exclude:
  - ebooks
  - pdf

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: false
  zamm:
    output: false
  smartphones:
    output: true
  restapicourse:
    output: false
  publishingapidocs:
    output: false
  voiceovertechniques:
    output: false
  visualcommunication:
    output: false
  podcasts:
    output: false
  youngadultnovel:
    output: false
  user_centered_doc:
    output: false

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: printpdf
      published: true
  -
    scope:
      path: ""
      type: smartphones
    values:
      layout: printpdf
      published: true
      collection: smartphones

  -
    scope:
      path: _docs/pdf_frontmatter
      type: docs
    values:
      layout: printpdf
      published: true
